import type { LevelConfig } from '@/game/config'

export const sampleLevels: LevelConfig[] = [
  {
    id: 1,
    title: '丢失的文具',
    difficulty: 'easy',
    storyIntro: '课间，同桌张三的铅笔盒不见了，他焦急地在教室里翻找...',
    mission: '帮助张三在教室后走廊找到丢失的文具',
    npcNeeds: '张三',
    postNote: '今天帮张三找到了妈妈送的铅笔，他笑得好开心。原来小小的举手之劳，也能照亮别人的一天。',
    noteDate: '1994-03-15',
    values: '善良',
    helpedPerson: '张三',
    action: '找到丢失的文具',
    location: '教室后走廊',
    stars: 3,
    choices: [
      { text: '直接帮他找', response: '张三感激地说："谢谢你！"', starBonus: 1 },
      { text: '先安慰他再找', response: '张三擦了擦眼泪："你真好..."', starBonus: 2, hiddenNote: '今天不仅找到了铅笔，还收获了一个朋友。' },
    ],
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 2,
    title: '雨天的伞',
    difficulty: 'easy',
    storyIntro: '放学时下起了大雨，李梅忘了带伞，站在教学楼门口发愁...',
    mission: '在迷宫般的教学楼中找到备用伞',
    npcNeeds: '李梅',
    postNote: '下雨天借给李梅一把伞，她第二天还伞时还带了一颗糖。善意就像涟漪，一圈圈荡开。',
    noteDate: '1994-04-02',
    values: '助人为乐',
    helpedPerson: '李梅',
    action: '借出雨伞',
    location: '教学楼大厅',
    stars: 3,
    choices: [
      { text: '把伞借给她', response: '李梅说："明天一定还你！"', starBonus: 1 },
      { text: '和她一起撑伞走', response: '李梅笑着说："顺路一起走吧~"', starBonus: 2, hiddenNote: '共撑一把伞走过雨天的校园，雨声也变得好听了。' },
    ],
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 3,
    title: '图书馆的难题',
    difficulty: 'easy',
    storyIntro: '王老师在图书馆整理书籍，但书架太高，很多书放不上去...',
    mission: '穿过书架迷宫，帮王老师整理高处的书籍',
    npcNeeds: '王老师',
    postNote: '帮王老师整理了半个图书馆的书，她夸我懂事。虽然胳膊有点酸，但看到整齐的书架，真开心。',
    noteDate: '1994-04-18',
    values: '尊师重道',
    helpedPerson: '王老师',
    action: '整理书籍',
    location: '学校图书馆',
    stars: 3,
    choices: [
      { text: '帮忙整理', response: '王老师欣慰地点点头', starBonus: 1 },
      { text: '帮忙整理并陪老师聊会天', response: '王老师讲起了年轻时当老师的故事...', starBonus: 2, hiddenNote: '听王老师讲了半辈子的教书故事，我突然明白了什么是坚守。' },
    ],
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 4,
    title: '操场边的等待',
    difficulty: 'medium',
    storyIntro: '一年级的小明在操场边哭泣，他的皮球滚进了杂物间...',
    mission: '穿越操场迷宫，进入杂物间找回小明的皮球',
    npcNeeds: '小明',
    postNote: '在杂物间找到了小明的皮球，他破涕为笑的样子真可爱。被需要的感觉，真好。',
    noteDate: '1994-05-06',
    values: '关爱幼小',
    helpedPerson: '小明',
    action: '找回皮球',
    location: '学校操场',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 5,
    title: '食堂的热汤',
    difficulty: 'medium',
    storyIntro: '食堂阿姨忙得不可开交，有同学打翻了汤碗...',
    mission: '穿过食堂迷宫，帮阿姨收拾并安慰同学',
    npcNeeds: '食堂阿姨',
    postNote: '帮阿姨收拾了打翻的汤，阿姨说我是好孩子，还多给我盛了一勺红烧肉。温暖是会传递的。',
    noteDate: '1994-05-20',
    values: '勤劳',
    helpedPerson: '食堂阿姨',
    action: '帮忙收拾',
    location: '学校食堂',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 6,
    title: '黑板报比赛',
    difficulty: 'medium',
    storyIntro: '班级黑板报比赛要开始了，文艺委员找不到足够的粉笔...',
    mission: '在走廊迷宫中寻找彩色粉笔',
    npcNeeds: '文艺委员',
    postNote: '跑遍了整条走廊才找到彩色粉笔，但看到我们班得了第一名，一切都值得。',
    noteDate: '1994-06-01',
    values: '集体荣誉',
    helpedPerson: '文艺委员',
    action: '寻找粉笔',
    location: '教学楼走廊',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 7,
    title: '实验课的意外',
    difficulty: 'hard',
    storyIntro: '物理实验课上，同桌不小心打碎了量筒...',
    mission: '穿越实验室迷宫，找到备用量筒',
    npcNeeds: '同桌小华',
    postNote: '帮小华在实验准备室找到了备用量筒，他的手还在抖。我说"没事的，谁都会犯错"。',
    noteDate: '1994-06-15',
    values: '宽容',
    helpedPerson: '小华',
    action: '寻找备用量筒',
    location: '物理实验室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 8,
    title: '秋天的落叶',
    difficulty: 'hard',
    storyIntro: '秋天到了，校园里落满了树叶，值日生一个人扫不完...',
    mission: '穿过校园迷宫，帮值日生清扫落叶',
    npcNeeds: '值日生',
    postNote: '和金鹏一起扫完了校园的落叶，秋天的阳光透过树枝洒下来，金灿灿的。劳动后的满足感，真好。',
    noteDate: '1994-10-10',
    values: '勤劳',
    helpedPerson: '金鹏',
    action: '清扫落叶',
    location: '校园大道',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 9,
    title: '运动会的水站',
    difficulty: 'hard',
    storyIntro: '运动会上，水站的志愿者中暑了...',
    mission: '穿过运动场迷宫，去水站帮忙',
    npcNeeds: '志愿者同学',
    postNote: '运动会那天热得要命，但我坚持在水站服务了一下午。每个来喝水的同学都说"谢谢"。',
    noteDate: '1994-10-28',
    values: '奉献',
    helpedPerson: '志愿者同学',
    action: '水站服务',
    location: '运动场',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 10,
    title: '最后的铃声',
    difficulty: 'hard',
    storyIntro: '学期最后一天，班主任的教案落在了办公室...',
    mission: '穿过教学楼迷宫，帮班主任取回教案',
    npcNeeds: '班主任',
    postNote: '帮李老师取回了教案，她摸着我的头说"这一年谢谢你"。我突然觉得，这所学校、这些人，已经深深刻在了我的记忆里。',
    noteDate: '1995-01-15',
    values: '感恩',
    helpedPerson: '李老师',
    action: '取回教案',
    location: '教师办公室',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 11,
    title: '失物招领',
    difficulty: 'medium',
    storyIntro: '失物招领处的物品堆积如山，值日生小芳完全不知道如何整理...',
    mission: '穿过储物室迷宫，帮小芳分类整理失物',
    npcNeeds: '小芳',
    postNote: '和小芳一起把失物招领处整理得井井有条，后来好多同学都找回了自己丢失的东西。有条理的感觉真好。',
    noteDate: '1994-09-10',
    values: '助人为乐',
    helpedPerson: '小芳',
    action: '整理失物招领处',
    location: '失物招领处',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 12,
    title: '广播体操',
    difficulty: 'medium',
    storyIntro: '体育老师需要人手帮忙准备广播体操的设备，音响和旗杆都需要搬到操场...',
    mission: '穿过体育器材室迷宫，帮体育老师搬运广播体操设备',
    npcNeeds: '体育老师',
    postNote: '帮老师搬了音响和旗杆，早操时全校同学跟着音乐做操，整齐划一的动作让人充满力量。',
    noteDate: '1994-09-18',
    values: '尊师重道',
    helpedPerson: '体育老师',
    action: '搬运广播设备',
    location: '体育器材室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 13,
    title: '美术课颜料',
    difficulty: 'medium',
    storyIntro: '美术课代表发现颜料盒里少了水彩颜料，大家等着用...',
    mission: '穿过美术教室迷宫，帮课代表找到水彩颜料',
    npcNeeds: '美术课代表',
    postNote: '在储藏柜深处找到了水彩颜料，大家画了一幅全班的大合照。画画的时候，教室里安静又温暖。',
    noteDate: '1994-09-25',
    values: '集体荣誉',
    helpedPerson: '美术课代表',
    action: '寻找水彩颜料',
    location: '美术教室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 14,
    title: '自行车倒了',
    difficulty: 'medium',
    storyIntro: '放学后车棚里一片狼藉，很多自行车被风吹倒了，小陈一个人扶不过来...',
    mission: '穿过车棚迷宫，帮小陈扶起倒下的自行车',
    npcNeeds: '小陈',
    postNote: '一辆辆把自行车扶起来，虽然手上沾了油污，但看到整齐的车棚，心里很亮堂。小陈说明天请我吃冰棍。',
    noteDate: '1994-10-05',
    values: '勤劳',
    helpedPerson: '小陈',
    action: '扶起自行车',
    location: '学校车棚',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 15,
    title: '英语磁带',
    difficulty: 'medium',
    storyIntro: '英语老师的听力课教材磁带找不到了，她急得在办公室直转圈...',
    mission: '穿过办公室迷宫，帮英语老师找到听力磁带',
    npcNeeds: '英语老师',
    postNote: '在磁带柜里找到了那盘老旧的英语磁带，放出来是纯正的英式发音。老师说这盘磁带陪了她十年。',
    noteDate: '1994-10-12',
    values: '尊师重道',
    helpedPerson: '英语老师',
    action: '寻找听力磁带',
    location: '教师办公室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 16,
    title: '春游准备',
    difficulty: 'medium',
    storyIntro: '春游前一天，班长发现准备好的急救包和野餐垫不见了...',
    mission: '穿过仓库迷宫，帮班长找到春游物资',
    npcNeeds: '班长',
    postNote: '和班长在仓库翻了好久才找到野餐垫和急救包，第二天大家在公园玩得特别开心。虽然累，但值得。',
    noteDate: '1994-10-20',
    values: '助人为乐',
    helpedPerson: '班长',
    action: '寻找春游物资',
    location: '学校仓库',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 17,
    title: '班级图书角',
    difficulty: 'medium',
    storyIntro: '班上要建一个图书角，图书管理员搬来了一大箱书需要分类上架...',
    mission: '穿过教室迷宫，帮图书管理员布置图书角',
    npcNeeds: '图书管理员',
    postNote: '按拼音把书一本本排好，图书角终于建成了。课间大家都来看书，那种安静阅读的氛围真好。',
    noteDate: '1994-10-30',
    values: '勤劳',
    helpedPerson: '图书管理员',
    action: '布置图书角',
    location: '教室图书角',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 18,
    title: '跳绳比赛',
    difficulty: 'medium',
    storyIntro: '体育委员要组织跳绳比赛，但比赛用的绳子少了一根...',
    mission: '穿过体育场迷宫，帮体育委员找到备用跳绳',
    npcNeeds: '体育委员',
    postNote: '在体育器材室找到了那根红色跳绳，比赛时大家跳得满头大汗。友谊第一，比赛第二。',
    noteDate: '1994-11-08',
    values: '集体荣誉',
    helpedPerson: '体育委员',
    action: '寻找跳绳',
    location: '体育器材室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 19,
    title: '植物浇水',
    difficulty: 'medium',
    storyIntro: '班级植物角的绿萝蔫了，负责浇水的同学生病了没来...',
    mission: '穿过教学楼迷宫，找到水壶帮植物浇水',
    npcNeeds: '生病同学',
    postNote: '替生病的同学给植物浇了水，绿萝又精神了。帮助别人的时候，也是在照顾自己的心。',
    noteDate: '1994-11-15',
    values: '关爱',
    helpedPerson: '生病同学',
    action: '给植物浇水',
    location: '教室植物角',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 20,
    title: '宿舍夜谈',
    difficulty: 'medium',
    storyIntro: '宿舍里小刘的被子掉到地上弄湿了，他冻得直哆嗦...',
    mission: '穿过宿舍楼迷宫，帮小刘找到备用被子',
    npcNeeds: '室友小刘',
    postNote: '从储物间帮小刘找来了备用被子，他感动得差点哭了。宿舍就像家，室友就是家人。',
    noteDate: '1994-11-22',
    values: '关爱',
    helpedPerson: '小刘',
    action: '寻找备用被子',
    location: '宿舍楼',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 21,
    title: '电脑课故障',
    difficulty: 'medium',
    storyIntro: '电脑课上，小周的电脑蓝屏了，作业还没保存，他急得满头大汗...',
    mission: '穿过电脑教室迷宫，帮小周找信息技术老师来修电脑',
    npcNeeds: '小周',
    postNote: '帮小周找到了信息技术老师，还好文件恢复了。他长舒一口气说"吓死我了"。数字化时代，数据就是命根子啊。',
    noteDate: '1994-12-03',
    values: '助人为乐',
    helpedPerson: '小周',
    action: '找老师修电脑',
    location: '电脑教室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 22,
    title: '校门口执勤',
    difficulty: 'medium',
    storyIntro: '轮到我们班在校门口执勤，小红却因为迟到被堵在了校门外...',
    mission: '穿过校门迷宫，帮小红完成执勤任务',
    npcNeeds: '小红',
    postNote: '和小红一起在校门口执勤，向每个进校的老师问好。一声声"老师好"里，藏着最朴素的尊师之情。',
    noteDate: '1994-12-10',
    values: '尊师重道',
    helpedPerson: '小红',
    action: '帮忙执勤',
    location: '学校大门',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 23,
    title: '音乐课乐器',
    difficulty: 'medium',
    storyIntro: '音乐老师要搬运一批新到的乐器到音乐教室，一个人忙不过来...',
    mission: '穿过音乐楼迷宫，帮音乐老师搬运乐器',
    npcNeeds: '音乐老师',
    postNote: '帮老师搬了小提琴和手风琴，音乐教室传来悠扬的琴声。音乐真是这世上最美妙的语言。',
    noteDate: '1994-12-18',
    values: '尊师重道',
    helpedPerson: '音乐老师',
    action: '搬运乐器',
    location: '音乐教室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 24,
    title: '数学作业本',
    difficulty: 'medium',
    storyIntro: '数学课代表抱着一大摞作业本，不小心撒了一地...',
    mission: '穿过走廊迷宫，帮课代表捡起散落的作业本',
    npcNeeds: '数学课代表',
    postNote: '蹲在地上和小玲一起捡作业本，有些同学的字写得歪歪扭扭，但每一本都是认真完成的。辛苦了，每一个努力的灵魂。',
    noteDate: '1995-01-05',
    values: '助人为乐',
    helpedPerson: '小玲',
    action: '捡作业本',
    location: '教学楼走廊',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 25,
    title: '校园广播站',
    difficulty: 'medium',
    storyIntro: '广播站的同学嗓子哑了，午间广播还没有准备好稿子...',
    mission: '穿过广播站迷宫，帮广播员准备稿子并代播',
    npcNeeds: '广播员小静',
    postNote: '第一次对着麦克风说话，声音传遍整个校园。虽然紧张得手心冒汗，但小静说我的声音很好听。',
    noteDate: '1995-01-12',
    values: '奉献',
    helpedPerson: '小静',
    action: '代播广播',
    location: '校园广播站',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 26,
    title: '地理课模型',
    difficulty: 'medium',
    storyIntro: '地理老师要展示地球仪和地形模型，但模型室的门锁打不开了...',
    mission: '穿过地理教室迷宫，找到备用钥匙打开模型室',
    npcNeeds: '地理老师',
    postNote: '终于在教务处借到了备用钥匙，地理老师用地球仪讲了大陆漂移说。那一刻，世界在我眼前转动。',
    noteDate: '1995-03-02',
    values: '尊师重道',
    helpedPerson: '地理老师',
    action: '寻找钥匙',
    location: '地理模型室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 27,
    title: '化学课试剂',
    difficulty: 'medium',
    storyIntro: '化学实验课上，小组的试剂瓶标签脱落了，分不清哪个是哪个...',
    mission: '穿过化学实验室迷宫，帮同学比对试剂瓶',
    npcNeeds: '实验小组同学',
    postNote: '用气味和颜色一一比对，终于分清了所有试剂。化学老师说我们有了科学家的精神。严谨，是最好的习惯。',
    noteDate: '1995-03-15',
    values: '勤劳',
    helpedPerson: '实验小组同学',
    action: '分拣试剂',
    location: '化学实验室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 28,
    title: '冬季长跑',
    difficulty: 'medium',
    storyIntro: '冬季长跑活动中，有同学跑岔气了，蹲在跑道边直不起腰...',
    mission: '穿过操场迷宫，扶岔气的同学去医务室',
    npcNeeds: '岔气同学',
    postNote: '扶着小陈慢慢走到医务室，校医说休息一会儿就好。看着他苍白的脸慢慢恢复血色，我松了口气。',
    noteDate: '1995-01-20',
    values: '关爱',
    helpedPerson: '小陈',
    action: '护送同学',
    location: '学校操场',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 29,
    title: '联欢会布置',
    difficulty: 'medium',
    storyIntro: '元旦联欢会要开始了，装饰彩带不够，文艺委员急得团团转...',
    mission: '穿过教学楼迷宫，去仓库找装饰彩带',
    npcNeeds: '文艺委员',
    postNote: '在仓库找到了彩带和气球，和同学们一起把教室布置得漂漂亮亮。联欢会上 everyone 笑得那么开心。',
    noteDate: '1994-12-30',
    values: '集体荣誉',
    helpedPerson: '文艺委员',
    action: '寻找装饰材料',
    location: '学校仓库',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 30,
    title: '毕业照',
    difficulty: 'medium',
    storyIntro: '拍毕业照那天，摄影师发现三脚架坏了，全班同学都在太阳下等着...',
    mission: '穿过校园迷宫，帮摄影师找到备用三脚架',
    npcNeeds: '摄影师',
    postNote: '从器材室扛来了备用三脚架，全班同学一起喊"茄子"的那一刻，我知道这是我永远珍藏的瞬间。',
    noteDate: '1995-06-20',
    values: '集体荣誉',
    helpedPerson: '摄影师',
    action: '寻找三脚架',
    location: '校园操场',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 31,
    title: '历史课道具',
    difficulty: 'medium',
    storyIntro: '历史课要演课本剧，但道具箱里的青铜器模型少了一件...',
    mission: '穿过历史教室迷宫，帮课代表找到丢失的道具',
    npcNeeds: '历史课代表',
    postNote: '在道具室角落找到了那个青铜器模型，演出很成功。历史的烟云在舞台上重现，台下一片掌声。',
    noteDate: '1995-04-08',
    values: '集体荣誉',
    helpedPerson: '历史课代表',
    action: '寻找道具',
    location: '历史教室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 32,
    title: '书法比赛',
    difficulty: 'medium',
    storyIntro: '书法比赛前，小林的墨汁打翻了，宣纸上满是墨渍...',
    mission: '穿过书法教室迷宫，帮小林找到新的墨汁和宣纸',
    npcNeeds: '小林',
    postNote: '赶紧去器材室帮小林拿了新墨汁和宣纸，他顺利完成了作品。看着他笔走龙蛇的样子，我暗暗佩服。',
    noteDate: '1995-04-15',
    values: '助人为乐',
    helpedPerson: '小林',
    action: '寻找文具',
    location: '书法教室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 33,
    title: '心理咨询',
    difficulty: 'hard',
    storyIntro: '同桌最近总是闷闷不乐，班主任让我去关心一下他...',
    mission: '穿过教学楼迷宫，找到同桌并陪他去心理咨询室',
    npcNeeds: '同桌',
    postNote: '陪同桌去了心理咨询室，他第一次说出了心里的烦恼。有时候，倾听就是最好的良药。',
    noteDate: '1995-04-22',
    values: '关爱',
    helpedPerson: '同桌',
    action: '陪伴倾听',
    location: '心理咨询室',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 34,
    title: '校园义卖',
    difficulty: 'medium',
    storyIntro: '学生会组织爱心义卖，但义卖用的桌子和遮阳伞还在仓库里...',
    mission: '穿过校园迷宫，帮学生会搬出义卖物资',
    npcNeeds: '学生会同学',
    postNote: '和同学们一起搬桌子、撑遮阳伞，义卖活动热闹非凡。卖出的每一分钱都会捐给山区的孩子。',
    noteDate: '1995-05-01',
    values: '奉献',
    helpedPerson: '学生会同学',
    action: '搬运物资',
    location: '校园广场',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 35,
    title: '手工课材料',
    difficulty: 'medium',
    storyIntro: '手工课上，小红发现彩纸和胶棒不够全班同学用了...',
    mission: '穿过教学楼迷宫，帮小红去储藏室拿材料',
    npcNeeds: '小红',
    postNote: '从储藏室抱来了彩纸和胶棒，大家折了千纸鹤和星星。满教室的彩色纸鹤，像极了我们的梦想。',
    noteDate: '1995-05-10',
    values: '助人为乐',
    helpedPerson: '小红',
    action: '搬运材料',
    location: '手工教室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 36,
    title: '雨中救书',
    difficulty: 'hard',
    storyIntro: '暴雨突然来袭，图书馆窗户没关，窗边的书马上要被淋湿了...',
    mission: '穿过图书馆迷宫，帮图书管理员关窗并抢救书籍',
    npcNeeds: '图书管理员',
    postNote: '冲进图书馆手忙脚乱地关窗搬书，虽然衣服湿透了，但所有的书都安然无恙。书比衣服重要。',
    noteDate: '1995-05-18',
    values: '勤劳',
    helpedPerson: '图书管理员',
    action: '抢救图书',
    location: '学校图书馆',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 37,
    title: '生物课标本',
    difficulty: 'hard',
    storyIntro: '生物实验室的蝴蝶标本被风吹落在地，翅膀碎了，生物课代表吓得不知所措...',
    mission: '穿过生物实验室迷宫，帮课代表修复标本',
    npcNeeds: '生物课代表',
    postNote: '小心地用镊子和胶水把蝴蝶翅膀一片片粘好，虽然有了裂痕，但依然美丽。残缺也是一种美。',
    noteDate: '1995-05-25',
    values: '勤劳',
    helpedPerson: '生物课代表',
    action: '修复标本',
    location: '生物实验室',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 38,
    title: '元旦贺卡',
    difficulty: 'medium',
    storyIntro: '元旦快到了，小雅写了很多贺卡要送给老师和同学，但来不及送去...',
    mission: '穿过教学楼迷宫，帮小雅把贺卡送到各个班级',
    npcNeeds: '小雅',
    postNote: '跑遍了整栋教学楼送贺卡，每个收到贺卡的人都笑得很开心。一张小小的卡片，传递的却是满满的心意。',
    noteDate: '1994-12-28',
    values: '关爱',
    helpedPerson: '小雅',
    action: '送贺卡',
    location: '教学楼',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 39,
    title: '校园清洁',
    difficulty: 'hard',
    storyIntro: '一场暴风雨过后，校园里遍地是断枝和落叶，清洁工阿姨一个人忙不过来...',
    mission: '穿过校园迷宫，帮清洁工阿姨清理校园',
    npcNeeds: '清洁工阿姨',
    postNote: '和阿姨一起清扫了整整一下午，满身的汗水和落叶。看着干净的校园，阿姨说"你们真是好孩子"。',
    noteDate: '1995-06-05',
    values: '勤劳',
    helpedPerson: '清洁工阿姨',
    action: '清扫校园',
    location: '校园',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 40,
    title: '爱心捐款',
    difficulty: 'medium',
    storyIntro: '学校为贫困地区的孩子组织捐款，班长需要人帮忙统计和整理捐款箱...',
    mission: '穿过教学楼迷宫，帮班长整理捐款',
    npcNeeds: '班长',
    postNote: '和班长一起数了整整一节课的零钱，虽然手酸，但每一分钱都是一颗爱心。世界因为善意而温暖。',
    noteDate: '1995-06-12',
    values: '善良',
    helpedPerson: '班长',
    action: '整理捐款',
    location: '教室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 41,
    title: '电教设备',
    difficulty: 'medium',
    storyIntro: '多媒体教室的投影仪不亮了，老师没办法上课...',
    mission: '穿过电教室迷宫，帮老师找到备用投影仪',
    npcNeeds: '电教老师',
    postNote: '和电教老师一起调试了半天，投影仪终于亮起来了。屏幕上出现知识的那一刻，我觉得科技真神奇。',
    noteDate: '1995-06-25',
    values: '尊师重道',
    helpedPerson: '电教老师',
    action: '调试投影仪',
    location: '多媒体教室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 42,
    title: '卫生室值班',
    difficulty: 'hard',
    storyIntro: '校医临时有事要出门，但卫生室里还有几个同学在等处理伤口...',
    mission: '穿过卫生室迷宫，帮校医整理药品并照顾同学',
    npcNeeds: '校医',
    postNote: '帮同学清洗了伤口、贴了创可贴，虽然笨手笨脚的，但大家都说我很温柔。原来照顾别人也是一种成长。',
    noteDate: '1995-07-02',
    values: '奉献',
    helpedPerson: '校医',
    action: '帮忙值班',
    location: '学校卫生室',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 43,
    title: '科技小发明',
    difficulty: 'medium',
    storyIntro: '科技节快到了，小刚的发明作品缺少一个关键零件...',
    mission: '穿过科技楼迷宫，帮小刚找到所需零件',
    npcNeeds: '小刚',
    postNote: '在科技楼的废旧器材堆里翻到了合适的零件，小刚的发明最终获得了二等奖。创新需要一双发现的眼睛。',
    noteDate: '1995-07-10',
    values: '助人为乐',
    helpedPerson: '小刚',
    action: '寻找零件',
    location: '科技楼',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 44,
    title: '校园植树',
    difficulty: 'hard',
    storyIntro: '植树节到了，工具不够用，很多同学只能用手挖土...',
    mission: '穿过校园迷宫，去仓库搬来铁锹和水桶',
    npcNeeds: '劳动委员',
    postNote: '扛着铁锹和水桶回来时，大家都欢呼起来。我们一起种下了十棵小树苗，多年以后它们会长成参天大树吧。',
    noteDate: '1995-03-12',
    values: '勤劳',
    helpedPerson: '劳动委员',
    action: '搬运工具',
    location: '校园绿化区',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 45,
    title: '辩论赛准备',
    difficulty: 'medium',
    storyIntro: '辩论赛马上就要开始了，四辩的稿子突然找不到了...',
    mission: '穿过教学楼迷宫，帮辩手找回丢失的辩论稿',
    npcNeeds: '辩手小文',
    postNote: '在打印室找到了被误拿的辩论稿，小文在台上侃侃而谈。语言的力量可以改变世界。',
    noteDate: '1995-07-20',
    values: '集体荣誉',
    helpedPerson: '小文',
    action: '寻找辩论稿',
    location: '教学楼',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 46,
    title: '晨读领读',
    difficulty: 'hard',
    storyIntro: '晨读时间，领读的同学嗓子发炎说不出话，教室里乱哄哄的...',
    mission: '穿过教室迷宫，代替领读带领全班晨读',
    npcNeeds: '领读同学',
    postNote: '鼓起勇气站上讲台领读了课文，刚开始声音有点抖，后来越读越大声。全班齐读的声音比任何独唱都动听。',
    noteDate: '1995-09-01',
    values: '奉献',
    helpedPerson: '领读同学',
    action: '代领晨读',
    location: '教室',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 47,
    title: '校园安全',
    difficulty: 'hard',
    storyIntro: '有同学发现操场的单杠螺丝松动了，随时可能倒下来...',
    mission: '穿过校园迷宫，找到维修师傅并张贴警示牌',
    npcNeeds: '维修师傅',
    postNote: '和维修师傅一起加固了单杠，贴上"已维修"的标签。安全无小事，每一个细节都关乎大家的健康。',
    noteDate: '1995-09-10',
    values: '奉献',
    helpedPerson: '维修师傅',
    action: '报修单杠',
    location: '学校操场',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 48,
    title: '教师节礼物',
    difficulty: 'hard',
    storyIntro: '教师节前一天，准备送给老师的礼物还在快递站没来得及取...',
    mission: '穿过校园迷宫，去快递站取回教师节礼物',
    npcNeeds: '班长',
    postNote: '赶在快递站关门前取回了礼物，大家把礼物送到老师面前时，老师眼眶红了。师恩如山，无以为报。',
    noteDate: '1995-09-09',
    values: '尊师重道',
    helpedPerson: '班长',
    action: '代取快递',
    location: '快递站',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 49,
    title: '秋游带队',
    difficulty: 'hard',
    storyIntro: '秋游时有个一年级的小朋友迷路了，带队老师急得直冒汗...',
    mission: '穿过公园迷宫，帮老师找到走丢的小朋友',
    npcNeeds: '带队老师',
    postNote: '在游乐区后面找到了正在哭的小朋友，牵着他的手走回队伍时，老师给了我一个大大的拥抱。被信任的感觉真好。',
    noteDate: '1995-10-15',
    values: '关爱幼小',
    helpedPerson: '带队老师',
    action: '寻找走失儿童',
    location: '秋游公园',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 50,
    title: '图书捐赠',
    difficulty: 'hard',
    storyIntro: '学校号召大家捐书给乡村小学，但捐赠的书籍需要分类打包...',
    mission: '穿过图书馆迷宫，帮老师整理打包捐赠书籍',
    npcNeeds: '图书馆老师',
    postNote: '和老师一起把几百本书分类、打包、装箱，每本书都承载着一个孩子的期待。知识应该被分享。',
    noteDate: '1995-10-25',
    values: '善良',
    helpedPerson: '图书馆老师',
    action: '整理打包书籍',
    location: '学校图书馆',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 51,
    title: '紧急疏散',
    difficulty: 'hard',
    storyIntro: '消防演练中，有位坐轮椅的同学被困在了教学楼三楼...',
    mission: '穿过教学楼迷宫，帮轮椅同学安全疏散到操场',
    npcNeeds: '坐轮椅的同学',
    postNote: '推着轮椅从三楼安全通道慢慢下楼，虽然胳膊酸了，但演练结束后他说谢谢。安全演练不是游戏，是救命的本领。',
    noteDate: '1995-11-05',
    values: '关爱',
    helpedPerson: '坐轮椅的同学',
    action: '协助疏散',
    location: '教学楼',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 52,
    title: '校园刊物',
    difficulty: 'hard',
    storyIntro: '校刊编辑部要赶在截稿日前完成排版，但主编病倒了...',
    mission: '穿过编辑部迷宫，帮校刊完成最后的校对和排版',
    npcNeeds: '校刊主编',
    postNote: '在编辑部和同学们一起校对了最后一期的稿子，闻着油墨的香味，文字的力量在心中流淌。',
    noteDate: '1995-11-15',
    values: '集体荣誉',
    helpedPerson: '校刊主编',
    action: '协助编辑校刊',
    location: '校刊编辑部',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 53,
    title: '期末复习',
    difficulty: 'hard',
    storyIntro: '期末考试临近，小刚因为生病落下了很多功课，急得直哭...',
    mission: '穿过教室迷宫，帮小刚整理复习笔记并讲解难题',
    npcNeeds: '小刚',
    postNote: '花了一整个周末帮小刚补习，他考试及格时第一个跑来告诉我。原来分享知识比独自优秀更快乐。',
    noteDate: '1996-01-10',
    values: '助人为乐',
    helpedPerson: '小刚',
    action: '辅导功课',
    location: '教室',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 54,
    title: '宿舍搬迁',
    difficulty: 'hard',
    storyIntro: '新学期宿舍调整，同学们的大件行李搬不动，在宿舍楼下发愁...',
    mission: '穿过宿舍区迷宫，帮同学们搬运行李到新宿舍',
    npcNeeds: '搬行李的同学',
    postNote: '来来回回搬了十几趟行李，汗水湿透了衣服。虽然累，但听到一声声"谢谢"，觉得浑身又有劲了。',
    noteDate: '1996-02-25',
    values: '助人为乐',
    helpedPerson: '搬行李的同学',
    action: '帮忙搬宿舍',
    location: '宿舍区',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 55,
    title: '校园文化节',
    difficulty: 'hard',
    storyIntro: '文化节开幕式在即，舞台的音响突然出了问题...',
    mission: '穿过文化广场迷宫，帮工作人员修复音响设备',
    npcNeeds: '文化节负责人',
    postNote: '和电工师傅一起排查线路，终于在开幕式前五分钟修好了音响。当音乐响起的那一刻，全场都沸腾了。',
    noteDate: '1996-03-20',
    values: '奉献',
    helpedPerson: '文化节负责人',
    action: '抢修音响',
    location: '文化广场',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 56,
    title: '志愿者服务',
    difficulty: 'hard',
    storyIntro: '社区服务活动中，敬老院的老人想给远方的孙子写信，但眼睛看不清了...',
    mission: '穿过敬老院迷宫，帮老人写信并寄出',
    npcNeeds: '敬老院老人',
    postNote: '握着老人的手一起写信，他讲了很多孙子小时候的故事。信寄出的那一刻，他眼里闪着泪光。陪伴是最长情的告白。',
    noteDate: '1996-04-08',
    values: '善良',
    helpedPerson: '敬老院老人',
    action: '代写家信',
    location: '社区敬老院',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 57,
    title: '寒夜暖粥',
    difficulty: 'hard',
    storyIntro: '寒冷的冬夜，宿舍里有同学感冒发烧，食堂已经关门了...',
    mission: '穿过校园迷宫，去食堂借厨房煮一碗热粥',
    npcNeeds: '生病的同学',
    postNote: '敲开了食堂的门，阿姨听说是给生病同学煮粥，二话不说就开了灶。端着热粥走回宿舍的路上，雪花落在碗里就化了。',
    noteDate: '1996-01-25',
    values: '关爱',
    helpedPerson: '生病的同学',
    action: '煮粥送暖',
    location: '食堂',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 58,
    title: '校园导游',
    difficulty: 'hard',
    storyIntro: '校园开放日来了很多家长，但学生导游人手不够...',
    mission: '穿过校园迷宫，带领家长参观学校并讲解',
    npcNeeds: '参观家长',
    postNote: '带着家长们走遍了校园的每一个角落，介绍我们引以为傲的图书馆、实验室。看到家长们赞许的目光，我为学校感到自豪。',
    noteDate: '1996-04-20',
    values: '奉献',
    helpedPerson: '参观家长',
    action: '校园导游',
    location: '校园',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 59,
    title: '辞旧迎新',
    difficulty: 'hard',
    storyIntro: '除夕前，学校需要人帮忙把旧教室的桌椅搬到新教学楼...',
    mission: '穿过教学楼迷宫，帮老师搬桌椅到新教室',
    npcNeeds: '总务老师',
    postNote: '和几个同学一起搬了整整一天的桌椅，虽然满头灰尘，但看着崭新的教室，心里充满了对新学期的期待。',
    noteDate: '1996-02-05',
    values: '勤劳',
    helpedPerson: '总务老师',
    action: '搬桌椅',
    location: '教学楼',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 60,
    title: '永远的约定',
    difficulty: 'hard',
    storyIntro: '毕业前夕，班长提议给二十年后的大家写一封信，放进班级时间胶囊...',
    mission: '穿过校园迷宫，收集每个同学的愿望信并封存时间胶囊',
    npcNeeds: '班长',
    postNote: '把全班同学的信封装进了时间胶囊，埋在了操场边的老槐树下。二十年后我们还会再相聚，那时的我们，会是怎样的呢。',
    noteDate: '1996-06-20',
    values: '集体荣誉',
    helpedPerson: '班长',
    action: '封存时间胶囊',
    location: '操场老槐树下',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
]
